name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-pylint faker python-dotenv  # Ensure all dependencies are installed

      - name: Run tests with pytest and enforce 100% coverage
        run: |
          pytest --cov=app --cov-fail-under=100  # Ensure coverage is checked for 'app' module or folder

      - name: Run linting with pylint
        run: |
          pylint app  # Run pylint directly on the 'app' folder or module

      - name: Run tests with --num_records
        run: |
          pytest --num_records=100  # Run tests with the custom num_records parameter
